---

- name: NFTables | Checking config
  ansible.builtin.assert:
    that:
      - nftables is defined

- name: NFTables | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"
