---

- name: Converge
  hosts: "test-ag-nftables-1"
  vars:
    nftables:
      enable:
        sets: false  # debian (11) kernel 5.x does not support it

      vars:
        global_var_test: '1.1.1.1'

      tables:
        example:
          vars:
            var_test: '1.1.1.1'
            private_ranges: ['192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8']
            dns_servers: ['1.1.1.1', '1.1.0.0', '8.8.8.8', '8.8.4.4']

          sets:
            set_test:
              flags: ['dynamic', 'timeout']
              settings:
                timeout: '3m'

          counters:
            invalid_packages:
              comment: 'Invalid'

          limits:
            icmp_limit:
              rate: '10/second'

          chains:
            incoming:
              vars:
                chain_var: '1.1.1.1'

              hook: 'input'
              rules:
                - sequence: 1
                  raw: 'ct state invalid counter name invalid_packages log prefix "DROP invalid sates" drop'
                - seq: 2
                  raw: 'ct state {established, related} counter accept comment "Allow open sessions"'
                - s: 3
                  raw: 'iifname "lo" accept comment "Allow loopback traffic"'
                - {proto: 'icmp', type: 'echo-request', limit: 'icmp_limit', comment: 'Allow icmp-ping'}
                - {proto: 'icmpv6', type: 'echo-request', limit: 'icmp_limit', comment: 'Allow icmp-ping'}
                - {proto: 'icmp', code: 30, limit: 'icmp_limit', comment: 'Allow icmp-traceroute'}
                - {proto: 'icmpv6', limit: 'icmp_limit', comment: 'Allow necessary icmpv6-types for ipv6 to work',
                   type: ['nd-neighbor-solicit', 'nd-router-advert', 'nd-neighbor-advert']}
                - {proto: 'udp', port: 46251, counter: 'invalid_packages', action: 'drop'}

            outgoing:
              hook: 'output'
              policy: 'accept'
              rules:
                - {dest: '$dns_servers', proto: 'udp', port: 53}
                - {dest: '$dns_servers', proto: 'tcp', port: [53, 853]}
                - {proto: ['tcp', 'udp'], port: [80, 443]}
                - {proto: ['icmp', 'icmpv6']}

            translate:
              hook: 'postrouting'
              type: 'nat'
              policy: 'accept'
              rules:
                - {'src': '$private_ranges', oif: 'eno2', masquerade: true}  # dynamic outbound nat
                - {'src': '$private_ranges', oif: 'eno3', snat: '192.168.0.1'}  # static outbound nat

  pre_tasks:
    - name: Installing Role dependencies
      apt:
        name: ['kmod']
        state: present

    - name: Test Utils
      apt:
        name: ['python3-nftables', 'nano']
        state: present

  roles:
    - ansibleguy.infra_nftables
