---

- name: Verify
  hosts: grp_tester
  gather_facts: false
  tasks:
    - name: Pulling existing rules
      ansible.builtin.command: 'nft list ruleset'
      register: ruleset

    - name: Checking rules
      ansible.builtin.assert:
        that:
          -
