---

- name: "NFTables | Debian | Table '{{ nft_table_name }}' | Chain '{{ nft_chain_name }}' | Checking config"
  ansible.builtin.assert:
    that: >
      nft_chain.type in NFT_HC.choises.chain.types and
      nft_chain.hook in NFT_HC.choises.hook[nft_table.type][nft_chain.type] and
      nft_chain.priority in NFT_HC.choises.priorities and
      nft_chain.rules |
      nftables_merge_rules(NFT_CONFIG, nft_table, nft_chain_name) |
      nftables_unique_sequence(NFT_HC.rules.sort)  # if rule sequences are unique
