---

- name: NFTables | Debian | Task
  ansible.builtin.apt:
    pkg: ['nftables']
    state: present

- name: NFTables | Debian | Adding config directory
  ansible.builtin.file:
    state: directory
    path: "{{ NFT_HC.path.config_dir }}"
    mode: 0750
    owner: 'root'
    group: 'root'

- name: NFTables | Debian | Copying base config
  ansible.builtin.template:
    src: "templates{{ NFT_HC.path.base_file }}"
    dest: "{{ NFT_HC.path.base_file }}"
    mode: 0640
    owner: 'root'
    group: 'root'
    validate: 'nft -cf %s'
  notify: Restart-nftables

- name: NFTables | Debian | Tables
  ansible.builtin.include_tasks: table.yml
  vars:
    nft_table_name: "{{ nft_table_item.key | nftables_safe_name }}"
    nft_table: "{{ defaults_table |
    combine(nftables._defaults.table) |
    combine(nft_table_item.value) }}"
  loop_control:
    loop_var: nft_table_item
  with_dict: "{{ NFT_CONFIG.tables }}"

- name: NFTables | Debian | Enabling/Starting service
  ansible.builtin.service:
    name: 'nftables.service'
    enabled: true
    state: started
